version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lavajato
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .docker/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lavajato-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "88:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    networks:
      - lavajato-network

networks:
  lavajato-network:
    driver: bridge
