services:
  db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
    volumes:
      - .docker/postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT_DB}:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${PORT_PGADMIN}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL_PGADMIN}
      - PGADMIN_DEFAULT_PASSWORD=${PASS_PGADMIN}
    volumes:
      - .docker/pgadmin_data:/var/lib/pgadmin
  